### ISSUE TITLE
NPEs on delete

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#34]
Deleted a parameter group that was referenced by a action facet. This should not happen, but if it does it should not NPE
 >org.opentravel.schemacompiler.validate.impl.TLValidatorBase.getPathParameterNames(TLValidatorBase.java:697)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.getMissingPathParams(TLValidatorBase.java:651)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validatePathTemplate(TLValidatorBase.java:623)
	at org.opentravel.schemacompiler.validate.compile.TLActionRequestCompileValidator.validateFields(TLActionRequestCompileValidator.java:91)
	at org.opentravel.schemacompiler.validate.compile.TLActionRequestCompileValidator.validateFields(TLActionRequestCompileValidator.java:40)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:123)
	at org.opentravel.schemacompiler.validate.impl.TLModelValidator.validateModelElement(TLModelValidator.java:74)
	at org.opentravel.schemacompiler.validate.compile.TLModelCompileValidator.validateModelElement(TLModelCompileValidator.java:116)
	at org.opentravel.schemas.node.resources.ResourceBase.isValid(ResourceBase.java:1

**Comment by xmldave** [comment]
the root cause is i was expecting an event when the parameter group was deleted but didn't get one. My workaround is to handle it directly in the delete code for param group. I should either use the compiler event (if added) or create a more event like handler.

**Comment by xmldave** [comment]
>> I had to learn how to use the ModelEventListener.  Now i am getting the remove events.
----- my notes----Compiler can ignore-------------
ownership events for ACTION_REQUEST_REMOVED are being received.
No events for:  
ACTION_REMOVED
ACTION_FACET_REMOVED
ACTION_RESPONSE_REMOVED
PARAM_GROUP_REMOVED
PARAMETER_REMOVED
>> These events are being thrown to the TLModel which i did not have a listener on.

On Create the only Ownership event is ACTION_REQUEST_ADDED
Testing on initial load from file (no GUI involvement) and looking for the object that have to have a listener on i saw that for TLParameter this is because the transformer is not setting the owner on the parameter group so the owning model is not found. line 365 in TLParameter bypasses throwing PARAMETER_ADDED.

**Comment by slivezey** [comment]
Fixed
