### ISSUE TITLE
ConcurrentModificationException when removing Resource from Library

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#35]
**After lots of cleanup and fixes, i still get these errors IF there are two resources that have some name overlaps. I have not isolated what fields.**  To replicate in the GUI create two resources from the same business object (like a modeler did an "oops") and then try to delete one.

ResourceNode.delete() - tlObj.getOwningLibrary().removeNamedMember(tlObj); throws the concurrent modification exception. I just started seeing this with managed libraries.

I thought the most likely cause is the GUI is leaving listeners on deleted children which are being invoked but deep checking did not find any.   While tracking this, i am finding that listeners are being called for objects that are in a different resource. there may be name collisions that are not reported.
 .. Value Change event: FACET_REF_MODIFIED this = Get_Request, old = ID, new = null event source is a TLParamGroup from the other resource in the other library.
No action is taken on the event. No changes made to the model.

> Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1067)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateParamGroup(ModelNavigator.java:666)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateResource(ModelNavigator.java:630)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateUserDefinedLibrary(ModelNavigator.java:362)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigate(ModelNavigator.java:114)
	at org.opentravel.schemacompiler.ic.EntityRemovedIntegrityChecker.purgeEntitiesFromModel(EntityRemovedIntegrityChecker.java:82)
	at org.opentravel.schemacompiler.ic.ModelElementRemovedIntegrityChecker.processModelEvent(ModelElementRemovedIntegrityChecker.java:66)
	at org.opentravel.schemacompiler.ic.ModelElementRemovedIntegrityChecker.processModelEvent(ModelElementRemovedIntegrityChecker.java:33)
	at org.opentravel.schemacompiler.ic.AbstractModelIntegrityChecker.processModelEvent(AbstractModelIntegrityChecker.java:61)
	at org.opentravel.schemacompiler.model.TLModel.publishEvent(TLModel.java:461)
	at org.opentravel.schemacompiler.model.TLModelElement.publishEvent(TLModelElement.java:87)
	at org.opentravel.schemacompiler.model.AbstractLibrary.removeNamedMember(AbstractLibrary.java:537)
	at org.opentravel.schemacompiler.model.TLLibrary.removeNamedMember(TLLibrary.java:379)
	at org.opentravel.schemas.node.resources.ResourceNode.delete(ResourceNode.java:227

**Comment by xmldave** [comment]
This one occurs when trying to do the master reset after having created Resources.

> Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1067)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateParamGroup(ModelNavigator.java:666)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateResource(ModelNavigator.java:630)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigateUserDefinedLibrary(ModelNavigator.java:362)
	at org.opentravel.schemacompiler.visitor.ModelNavigator.navigate(ModelNavigator.java:114)
	at org.opentravel.schemacompiler.ic.EntityRemovedIntegrityChecker.purgeEntitiesFromModel(EntityRemovedIntegrityChecker.java:82)
	at org.opentravel.schemacompiler.ic.LibraryRemovedIntegrityChecker.processModelEvent(LibraryRemovedIntegrityChecker.java:38)
	at org.opentravel.schemacompiler.ic.LibraryRemovedIntegrityChecker.processModelEvent(LibraryRemovedIntegrityChecker.java:29)
	at org.opentravel.schemacompiler.ic.AbstractModelIntegrityChecker.processModelEvent(AbstractModelIntegrityChecker.java:61)
	at org.opentravel.schemacompiler.model.TLModel.publishEvent(TLModel.java:461)
	at org.opentravel.schemacompiler.model.TLModel.removeLibrary(TLModel.java:186)
	at org.opentravel.schemacompiler.repository.ProjectManager.purgeOrphanedProjectItems(ProjectManager.java:2154)
	at org.opentravel.schemacompiler.repository.ProjectManager.closeProject(ProjectManager.java:624)
	at org.opentravel.schemas.controllers.DefaultProjectController.close(DefaultProjectController.java:622)
	at org.opentravel.schemas.controllers.DefaultProjectController.refreshMaster(DefaultProjectController.java:652)
	at org.opentravel.schemas.controllers.MainController.refreshMaster(MainController.java:442)
	at org.opentravel.schemas.commands.RefreshViewHandler.execute(RefreshViewHandler.java:42)
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)

**Comment by slivezey** [comment]
Fixed
