### ISSUE TITLE
NPE on validation

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#40]
I am not sure how to repeat this...i have two libraries, one Steve's test library (attached) with core objects that extend other core objects and have choice facets as types.

When i use the SampleCore to set an extension on a core in a different library, i get this npe only if it is the first time an extension is set. Tracing in the debugger shows that versionedEntity is null.

        // Determine whether the candidate is a version or non-version extension
        if (candidateVersion != null) {
            if (versionedEntity.getBaseNamespace().equals(candidateVersion.getBaseNamespace())) {
                String versionedEntityName = (versionedEntity instanceof TLOperation) ?

[testFile6.zip](https://github.com/OpenTravel/OTM-DE-Compiler/files/190970/testFile6.zip)

-------------------------------------
java.lang.NullPointerException
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.getExtendedVersion(TLValidatorBase.java:327)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.isVersionExtension(TLValidatorBase.java:281)
	at org.opentravel.schemacompiler.validate.compile.TLAttributeCompileValidator.validateFields(TLAttributeCompileValidator.java:105)
	at org.opentravel.schemacompiler.validate.compile.TLAttributeCompileValidator.validateFields(TLAttributeCompileValidator.java:49)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:123)
	at org.opentravel.schemacompiler.validate.base.TLFacetBaseValidator.validateChildren(TLFacetBaseValidator.java:55)
	at org.opentravel.schemacompiler.validate.base.TLFacetBaseValidator.validateChildren(TLFacetBaseValidator.java:32)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLCoreObjectBaseValidator.validateChildren(TLCoreObjectBaseValidator.java:80)
	at org.opentravel.schemacompiler.validate.base.TLCoreObjectBaseValidator.validateChildren(TLCoreObjectBaseValidator.java:35)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validateChildren(TLLibraryBaseValidator.java:71)
	at org.opentravel.schemacompiler.validate.compile.TLLibraryCompileValidator.validateChildren(TLLibraryCompileValidator.java:124)
	at org.opentravel.schemacompiler.validate.compile.TLLibraryCompileValidator.validateChildren(TLLibraryCompileValidator.java:41)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validate(TLLibraryBaseValidator.java:43)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validate(TLLibraryBaseValidator.java:32)
	at org.opentravel.schemacompiler.validate.impl.TLModelValidator.validateModelElement(TLModelValidator.java:74)
	at org.opentravel.schemacompiler.validate.compile.TLModelCompileValidator.validateModelElement(TLModelCompileValidator.java:116)
	at org.opentravel.schemas.node.Node.validate(Node.java:3006)

**Comment by slivezey** [comment]
I will add some defensive code to prevent the NPE from happening, but I think the root cause of this error is that the attribute's owner is not assigned prior to running the validation.  If that is the case, it is possible that the validation will miss an error that cannot be identified until after the owner is assigned.
