### ISSUE TITLE
NPE on validation when UPA violation

### ISSUE THREAD

**Issue by xmldave** [OpenTravel/OTM-DE-Compiler#41]
Working on setting base types on core objects:

java.lang.NullPointerException
	at org.opentravel.schemacompiler.validate.impl.UPAViolationChecker.getPossibleElementNames(UPAViolationChecker.java:260)
	at org.opentravel.schemacompiler.validate.impl.UPAViolationChecker.<init>(UPAViolationChecker.java:124)
	at org.opentravel.schemacompiler.validate.impl.UPAViolationChecker.<init>(UPAViolationChecker.java:75)
	at org.opentravel.schemacompiler.validate.compile.TLPropertyCompileValidator.getUPAViolationChecker(TLPropertyCompileValidator.java:280)
	at org.opentravel.schemacompiler.validate.compile.TLPropertyCompileValidator.validateFields(TLPropertyCompileValidator.java:149)
	at org.opentravel.schemacompiler.validate.compile.TLPropertyCompileValidator.validateFields(TLPropertyCompileValidator.java:63)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:123)
	at org.opentravel.schemacompiler.validate.base.TLFacetBaseValidator.validateChildren(TLFacetBaseValidator.java:62)
	at org.opentravel.schemacompiler.validate.base.TLFacetBaseValidator.validateChildren(TLFacetBaseValidator.java:32)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLCoreObjectBaseValidator.validateChildren(TLCoreObjectBaseValidator.java:80)
	at org.opentravel.schemacompiler.validate.base.TLCoreObjectBaseValidator.validateChildren(TLCoreObjectBaseValidator.java:35)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validateChildren(TLLibraryBaseValidator.java:71)
	at org.opentravel.schemacompiler.validate.compile.TLLibraryCompileValidator.validateChildren(TLLibraryCompileValidator.java:124)
	at org.opentravel.schemacompiler.validate.compile.TLLibraryCompileValidator.validateChildren(TLLibraryCompileValidator.java:41)
	at org.opentravel.schemacompiler.validate.impl.TLValidatorBase.validate(TLValidatorBase.java:124)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validate(TLLibraryBaseValidator.java:43)
	at org.opentravel.schemacompiler.validate.base.TLLibraryBaseValidator.validate(TLLibraryBaseValidator.java:32)
	at org.opentravel.schemacompiler.validate.impl.TLModelValidator.validateModelElement(TLModelValidator.java:74)
	at org.opentravel.schemacompiler.validate.compile.TLModelCompileValidator.validateModelElement(TLModelCompileValidator.java:116)
	at org.opentravel.schemas.node.Node.validate(Node.java:2732)

**Comment by slivezey** [comment]
I have added some defensive code to avoid the NPE, but I suspect the root cause is a core object that has not yet been added to the model at the time this validation occurs.  Since UPA's are highly sensitive to the position and name of XML elements, it is possible (in extreme edge cases) that the NPE fix could cause some UPA errors to be missed and others to be falsely reported.
